services:
  - type: web
    name: your-app-name
    env: docker
    dockerfilePath: Dockerfile
    buildCommand: bundle install && yarn install && bundle exec rails assets:precompile
    startCommand: bundle exec rails server -b 0.0.0.0
    envVars:
      - key: DATABASE_URL
        value: postgres://tuning_app_user:zrpXotYxFNsTE35pIlMBsi5SCstxpQ4B@dpg-cpck5pm3e1ms73evb8gg-a/tuning_app